hw-03-mongo-db-mongoose-for-checking
vplabunets/nodejs-homework-rest-api pull request #3
Opened 2023-01-14 11:45 UTC by vplabunets

Третя домашня робота готова до перевірки.

2023-01-14 13:24 UTC, KhYulian commented on app.js
>        message: err.message,
Можна скоротити. Використайте ||

2023-01-14 13:25 UTC, KhYulian commented on controllers/contacts.controllers.js
> +  }
Використайте Joi схему та middleware для валідації

2023-01-14 13:25 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-15 11:45 UTC, vplabunets commented on controllers/contacts.controllers.js
> +  }
Так в мене використовується Joi схема:
 const updateContactStatusSchema = Joi.object({
  favorite: Joi.boolean(),
});

2023-01-15 11:47 UTC, vplabunets commented on app.js
>        message: err.message,
Виправив

2023-01-15 13:40 UTC, KhYulian commented on controllers/contacts.controllers.js
> +  }
Якщо Joi вже валідує поля, тоді ця перевірка просто зайва

2023-01-15 14:50 UTC, vplabunets commented on controllers/contacts.controllers.js
> +  }
видалив зайву перевірку.

2023-01-15 20:58 UTC, merged